# Auto-generated by R26-SE-038 Component 3
# Function : divide
# Source   : sample_project/calculator.py
# Valid    : True
# Repairs  : 0
# Run ID   : demo-run-001

import pytest
from sample_project.calculator import divide

def test_divide_normal_case():
    assert divide(10, 2) == 5

def test_divide_zero_numerator():
    assert divide(0, 10) == 0

def test_divide_negative_numbers():
    assert divide(-10, 2) == -5
    assert divide(10, -2) == -5
    assert divide(-10, -2) == 5

def test_divide_floats():
    assert divide(10.5, 2) == 5.25
    assert divide(10, 2.5) == 4

def test_divide_by_zero():
    with pytest.raises(ZeroDivisionError):
        divide(10, 0)

def test_divide_non_numeric_input():
    with pytest.raises(TypeError):
        divide('a', 2)
    with pytest.raises(TypeError):
        divide(10, 'b')
    with pytest.raises(TypeError):
        divide('a', 'b')