# Auto-generated by R26-SE-038 Component 3
# Function : divide
# Source   : sample_project/calculator.py
# Valid    : True
# Repairs  : 0
# Run ID   : 679d0339

import pytest
from sample_project.calculator import divide

def test_divide_normal_case():
    assert divide(10, 2) == 5

def test_divide_negative_numbers():
    assert divide(-10, 2) == -5
    assert divide(10, -2) == -5
    assert divide(-10, -2) == 5

def test_divide_zero():
    assert divide(0, 10) == 0
    assert divide(10, 0) is None

def test_divide_floats():
    assert divide(10.5, 2) == 5.25
    assert divide(10, 2.5) == 4

def test_divide_division_by_zero():
    with pytest.raises(ZeroDivisionError):
        divide(10, 0)

def test_divide_non_numeric_input():
    with pytest.raises(TypeError):
        divide("10", 2)
    with pytest.raises(TypeError):
        divide(10, "2")

def test_divide_non_integer_divisor():
    assert divide(10, 3) == 10 / 3

def test_divide_large_numbers():
    assert divide(1000000, 2) == 500000
    assert divide(1000000, 1000000) == 1

def test_divide_small_numbers():
    assert divide(0.000001, 2) == 0.0000005
    assert divide(0.000001, 0.000001) == 1