# Auto-generated by R26-SE-038 Component 3
# Function : check_header_validity
# Source   : src/requests/utils.py
# Valid    : True
# Repairs  : 0
# Run ID   : requests-demo-001

import pytest
from requests.exceptions import InvalidHeader
from requests._internal_utils import _HEADER_VALIDATORS_STR, _HEADER_VALIDATORS_BYTE

# Define test data
valid_headers = [
    ("Content-Type", "application/json"),
    ("Accept", "text/plain"),
    ("User-Agent", "Mozilla/5.0"),
]

invalid_headers = [
    (" Content-Type", "application/json"),  # leading whitespace in name
    ("Content-Type ", "application/json"),  # trailing whitespace in name
    ("Content-Type", " application/json"),  # leading whitespace in value
    ("Content-Type", "application/json "),  # trailing whitespace in value
    ("Content-Type", "\napplication/json"),  # newline in value
    ("Content-Type", "\rapplication/json"),  # return in value
    ("Content-Type", "\tapplication/json"),  # tab in value
]

def test_check_header_validity_valid_headers():
    for header in valid_headers:
        try:
            check_header_validity(header)
        except InvalidHeader as e:
            pytest.fail(f"Unexpected InvalidHeader exception: {e}")

def test_check_header_validity_invalid_headers():
    for header in invalid_headers:
        with pytest.raises(InvalidHeader):
            check_header_validity(header)

def test_check_header_validity_invalid_header_type():
    invalid_header = (b"Content-Type", "application/json")
    with pytest.raises(InvalidHeader):
        check_header_validity(invalid_header)

def test_check_header_validity_invalid_value_type():
    invalid_header = ("Content-Type", b"application/json")
    with pytest.raises(InvalidHeader):
        check_header_validity(invalid_header)

def test_check_header_validity_empty_header():
    empty_header = ("", "")
    with pytest.raises(InvalidHeader):
        check_header_validity(empty_header)

def test_check_header_validity_none_header():
    none_header = (None, "application/json")
    with pytest.raises(InvalidHeader):
        check_header_validity(none_header)

def test_check_header_validity_invalid_name():
    invalid_name = (" Content-Type", "application/json")
    with pytest.raises(InvalidHeader):
        check_header_validity(invalid_name)

def test_check_header_validity_invalid_value():
    invalid_value = ("Content-Type", " application/json")
    with pytest.raises(InvalidHeader):
        check_header_validity(invalid_value)