# Auto-generated by R26-SE-038 Component 3
# Function : validate_payment
# Valid    : True
# Repairs  : 0
# Run ID   : 91db9fe5

import pytest
from src.payment import validate_payment

def test_tc001_valid_payment_integer_amount():
    result = validate_payment(amount=100, currency='USD', user_id='user123')
    assert result == (True, 'Valid')

def test_tc002_valid_payment_float_amount():
    result = validate_payment(amount=0.01, currency='EUR', user_id=42)
    assert result == (True, 'Valid')

def test_tc003_valid_payment_large_integer_amount():
    result = validate_payment(amount=5000, currency='GBP', user_id='uid_9876')
    assert result == (True, 'Valid')