# Auto-generated by R26-SE-038 Component 3
# Function : format_receipt
# Valid    : True
# Repairs  : 0
# Run ID   : 91db9fe5

import pytest
from src.output import format_receipt

def test_tc001_normal_all_fields_present_default_include_tax():
    transaction = {'status': 'completed', 'currency': 'USD', 'amount': 123.456}
    result = format_receipt(transaction, include_tax=True)
    expected = "Transaction: completed\nAmount: USD 123.46\nTax included in total"
    assert result == expected

def test_tc002_normal_include_tax_false_missing_fields():
    transaction = {'currency': 'EUR'}
    result = format_receipt(transaction, include_tax=False)
    expected = "Transaction: unknown\nAmount: EUR 0.00"
    assert result == expected

def test_tc003_normal_empty_transaction_default_include_tax():
    transaction = {}
    result = format_receipt(transaction, include_tax=True)
    expected = "Transaction: unknown\nAmount:  0.00\nTax included in total"
    assert result == expected