# Auto-generated by R26-SE-038 Component 3
# Function : divide
# Source   : sample_project/calculator.py
# Valid    : True
# Repairs  : 0
# Run ID   : demo-run-001

import pytest
from sample_project.calculator import divide

def test_divide_normal_case():
    assert divide(10, 2) == 5

def test_divide_zero_dividend():
    assert divide(0, 10) == 0

def test_divide_zero_divisor():
    with pytest.raises(ZeroDivisionError):
        divide(10, 0)

def test_divide_negative_dividend():
    assert divide(-10, 2) == -5

def test_divide_negative_divisor():
    assert divide(10, -2) == -5

def test_divide_negative_both():
    assert divide(-10, -2) == 5

def test_divide_float_dividend():
    assert divide(10.5, 2) == 5.25

def test_divide_float_divisor():
    assert divide(10, 2.5) == 4

def test_divide_float_both():
    assert divide(10.5, 2.5) == 4.2