# Auto-generated by R26-SE-038 Component 3
# Function : get_encoding_from_headers
# Source   : src/requests/utils.py
# Valid    : True
# Repairs  : 2
# Run ID   : requests-demo-001

import pytest
from urllib.parse import urlparse
from http import HTTPStatus
from requests.exceptions import InvalidURL
from requests.models import PreparedRequest
from requests.structures import CaseInsensitiveDict
import codecs

def get_encoding_from_headers(headers):
    content_type = headers.get("content-type")

    if not content_type:
        return None

    encoding = parse_header(content_type).get("charset")

    if encoding:
        encoding = encoding.strip("'\"")

    if encoding and codecs.lookup(encoding):
        return encoding

    return None

def parse_header(header_string):
    """Parse a Content-Type like header.

    :param header_string: The header string to parse.
    :type header_string: str

    :return: A dictionary containing the parsed key/value pairs
    :rtype: dict
    """
    result = {}
    items = header_string.split(',')
    for item in items:
        params = {}
        key_value = item.split(';')
        key = key_value[0].strip()
        if key:
            value = ''
            for param in key_value[1:]:
                param = param.strip()
                if param:
                    p_key_value = param.split('=')
                    p_key = p_key_value[0].strip()
                    p_value = p_key_value[1].strip().strip("'\"")
                    params[p_key] = p_value
            result[key] = value
            if params:
                result[key] = params
    return result

def test_get_encoding_from_headers_no_content_type():
    headers = CaseInsensitiveDict()
    assert get_encoding_from_headers(headers) is None

def test_get_encoding_from_headers_no_charset():
    headers = CaseInsensitiveDict({"content-type": "text/plain"})
    assert get_encoding_from_headers(headers) is None

def test_get_encoding_from_headers_with_charset():
    headers = CaseInsensitiveDict({"content-type": "text/plain; charset=utf-8"})
    assert get_encoding_from_headers(headers) == "utf-8"

def test_get_encoding_from_headers_with_charset_and_quotes():
    headers = CaseInsensitiveDict({"content-type": 'text/plain; charset="utf-8"'})
    assert get_encoding_from_headers(headers) == "utf-8"

def test_get_encoding_from_headers_with_charset_and_apostrophes():
    headers = CaseInsensitiveDict({"content-type": "text/plain; charset='utf-8'"})
    assert get_encoding_from_headers(headers) == "utf-8"

def test_get_encoding_from_headers_with_invalid_charset():
    headers = CaseInsensitiveDict({"content-type": "text/plain; charset=invalid"})
    assert get_encoding_from_headers(headers) is None

def test_get_encoding_from_headers_with_multiple_charsets():
    headers = CaseInsensitiveDict({"content-type": "text/plain; charset=utf-8, iso-8859-1"})
    assert get_encoding_from_headers(headers) == "utf-8"

def test_get_encoding_from_headers_with_empty_charset():
    headers = CaseInsensitiveDict({"content-type": "text/plain; charset="})
    assert get_encoding_from_headers(headers) == ""

def test_get_encoding_from_headers_with_none_charset():
    headers = CaseInsensitiveDict({"content-type": "text/plain; charset=None"})
    assert get_encoding_from_headers(headers) == "None"

def test_get_encoding_from_headers_with_invalid_header():
    headers = CaseInsensitiveDict({"content-type": "invalid"})
    assert get_encoding_from_headers(headers) is None

def test_get_encoding_from_headers_with_empty_header():
    headers = CaseInsensitiveDict({"content-type": ""})
    assert get_encoding_from_headers(headers) is None

def test_get_encoding_from_headers_with_none_header():
    headers = CaseInsensitiveDict({"content-type": None})
    assert get_encoding_from_headers(headers) is None