# Auto-generated by R26-SE-038 Component 3
# Function : prepend_scheme_if_needed
# Source   : src/requests/utils.py
# Valid    : True
# Repairs  : 0
# Run ID   : requests-demo-001

import pytest
from requests.utils import prepend_scheme_if_needed, urlparse, urlunparse, parse_url

def test_prepend_scheme_if_needed_no_scheme():
    url = "example.com"
    new_scheme = "https"
    expected_url = "https://example.com"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_with_scheme():
    url = "http://example.com"
    new_scheme = "https"
    expected_url = "http://example.com"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_with_auth():
    url = "example.com"
    new_scheme = "https"
    expected_url = "https://example.com"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

    url = "user:pass@example.com"
    new_scheme = "https"
    expected_url = "https://user:pass@example.com"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_with_port():
    url = "example.com:8080"
    new_scheme = "https"
    expected_url = "https://example.com:8080"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_with_path():
    url = "example.com/path"
    new_scheme = "https"
    expected_url = "https://example.com/path"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_with_query():
    url = "example.com?query=param"
    new_scheme = "https"
    expected_url = "https://example.com?query=param"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_with_fragment():
    url = "example.com#fragment"
    new_scheme = "https"
    expected_url = "https://example.com#fragment"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_with_all_components():
    url = "user:pass@example.com:8080/path?query=param#fragment"
    new_scheme = "https"
    expected_url = "https://user:pass@example.com:8080/path?query=param#fragment"
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_empty_url():
    url = ""
    new_scheme = "https"
    expected_url = ""
    assert prepend_scheme_if_needed(url, new_scheme) == expected_url

def test_prepend_scheme_if_needed_none_url():
    url = None
    new_scheme = "https"
    with pytest.raises(TypeError):
        prepend_scheme_if_needed(url, new_scheme)

def test_prepend_scheme_if_needed_none_new_scheme():
    url = "example.com"
    new_scheme = None
    with pytest.raises(TypeError):
        prepend_scheme_if_needed(url, new_scheme)

def test_prepend_scheme_if_needed_invalid_url():
    url = "invalid_url"
    new_scheme = "https"
    with pytest.raises(ValueError):
        prepend_scheme_if_needed(url, new_scheme)