import json
from typing import Dict, Any

class LLMPromptGenerator:
    """
    Generates a structured prompt for a Large Language Model (LLM) based on the 
    prioritization payload generated by TestPrioritizer.
    This prepares the risk scores and prioritized code for Component 3.
    """

    @staticmethod
    def generate_prompt(payload: Dict[str, Any]) -> str:
        """
        Takes the prioritization payload and formats it into a text prompt 
        for an LLM to generate test cases, prioritizing risky codes first.
        """
        project_name = payload.get("project", "unknown project")
        summary = payload.get("summary", {})
        ranked_functions = payload.get("ranked_functions", [])

        prompt = (
            f"You are an expert AI Software Testing Assistant. Your task is to generate test cases "
            f"for a codebase (Project: {project_name}). We have analyzed the code using an ML Risk Detector "
            f"and prioritized the functions based on their risk of containing defects.\n\n"
        )
        
        prompt += (
            f"### Risk Summary\n"
            f"- Total Functions Analyzed: {summary.get('total_functions', 0)}\n"
            f"- High Risk: {summary.get('high_risk_count', 0)} ({summary.get('high_risk_pct', 0)}%)\n"
            f"- Medium Risk: {summary.get('medium_risk_count', 0)}\n"
            f"- Low Risk: {summary.get('low_risk_count', 0)}\n\n"
        )
        
        prompt += (
            "Please focus your testing efforts on the High Risk functions first, followed by Medium Risk. "
            "For High Risk functions, generate exhaustive tests including boundary conditions, edge cases, and negative tests. "
            "For Medium Risk functions, focus on boundary tests and typical inputs. "
            "For Low Risk functions, basic happy-path tests are sufficient.\n\n"
        )

        prompt += "### Prioritized Functions (Ranked by Risk Score)\n\n"

        for func in ranked_functions:
            func_name = func.get('function_name', 'Unknown')
            risk_level = func.get('risk_level', 'UNKNOWN')
            risk_score = func.get('risk_score', 0.0)
            file_path = func.get('file_path', '')
            start_line = func.get('start_line', '')
            end_line = func.get('end_line', '')
            explanation = func.get('explanation_text', '')
            test_types = ", ".join(func.get('test_types', []))

            prompt += (
                f"#### [{func.get('priority_rank', 0)}] Function: `{func_name}` ({risk_level} Risk)\n"
                f"- **Location:** `{file_path}` (Lines {start_line}-{end_line})\n"
                f"- **Risk Score:** {risk_score:.3f}\n"
                f"- **Test Strategy:** {func.get('recommended_test_depth', 'basic')} ({test_types})\n"
                f"- **Risk Explanation:** {explanation}\n"
            )

            top_factors = func.get('top_risk_factors', [])
            if top_factors:
                prompt += "- **Key Risk Factors (SHAP):**\n"
                for factor in top_factors:
                    prompt += f"  - `{factor['feature']}`: {factor['value']} (Impact: {factor['contribution']:+.3f})\n"
            
            prompt += "\n"
            
        prompt += (
            "---\n"
            "Based on the above prioritization, please generate the corresponding test cases in Python using pytest. "
            "Start with the function ranked #1."
        )

        return prompt

    @staticmethod
    def export_prompt(payload: Dict[str, Any], path: str) -> None:
        """Writes the generated LLM prompt to a file."""
        prompt_text = LLMPromptGenerator.generate_prompt(payload)
        with open(path, "w", encoding="utf-8") as f:
            f.write(prompt_text)
