"""
src/utils/output_writer.py
───────────────────────────
Saves pipeline results to disk.

Produces per run:
  1. A .py test file for each validated segment
  2. A JSON code review report
  3. A JSON traceability report (NEW)
  4. A JSON run summary
"""

import json
import logging
from pathlib import Path
from datetime import datetime

from src.models.schemas import PipelineOutput

logger = logging.getLogger(__name__)


class OutputWriter:
    def __init__(self, output_dir: str = "./outputs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"OutputWriter ready | dir={self.output_dir}")

    def save(self, output: PipelineOutput) -> dict:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_dir = self.output_dir / f"run_{output.run_id}_{timestamp}"
        run_dir.mkdir(parents=True, exist_ok=True)

        tests_path = run_dir / "generated_tests"
        tests_path.mkdir(exist_ok=True)

        written_files = {
            "test_files": [],
            "review_report": None,
            "traceability_report": None,
            "summary": None,
        }

        # ── 1. Save test files ─────────────────────────────────────────────
        for test in output.validated_tests:
            if not test.validated_test_code.strip():
                continue

            file_name = f"test_{test.function_name}.py"
            file_path = tests_path / file_name

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"# Auto-generated by R26-SE-038 Component 3\n")
                f.write(f"# Function : {test.function_name}\n")
                f.write(f"# Valid    : {test.is_syntactically_valid}\n")
                f.write(f"# Repairs  : {test.total_repairs}\n")
                f.write(f"# Run ID   : {output.run_id}\n\n")
                f.write(test.validated_test_code)

            written_files["test_files"].append(str(file_path))
            logger.info(f"Saved test file: {file_path}")

        # ── 2. Save code review report ─────────────────────────────────────
        review_data = {
            "run_id": output.run_id,
            "generated_at": timestamp,
            "repository": output.repository_path,
            "reports": [
                {
                    "segment_id": r.segment_id,
                    "function_name": r.function_name,
                    "file_path": r.file_path,
                    "pylint_score": r.pylint_score,
                    "summary": r.summary,
                    "total_findings": r.total_findings,
                    "findings": [
                        {
                            "finding_id": f.finding_id,
                            "category": f.category.value,
                            "severity": f.severity.value,
                            "line_number": f.line_number,
                            "description": f.description,
                            "suggested_fix": f.suggested_fix,
                        }
                        for f in r.findings
                    ],
                }
                for r in output.code_review_reports
            ],
        }

        review_path = run_dir / "code_review_report.json"
        with open(review_path, "w", encoding="utf-8") as f:
            json.dump(review_data, f, indent=2)
        written_files["review_report"] = str(review_path)
        logger.info(f"Saved review report: {review_path}")

        # ── 3. Save traceability report (NEW) ─────────────────────────────
        traceability_data = {
            "run_id": output.run_id,
            "generated_at": timestamp,
            "segments": [],
        }

        for test in output.validated_tests:
            segment_trace = {
                "segment_id": test.segment_id,
                "function_name": test.function_name,
                "traceability": None,
            }

            if test.traceability_report:
                tr = test.traceability_report
                segment_trace["traceability"] = {
                    "total_test_cases": tr.total_test_cases,
                    "covered_count": tr.covered_count,
                    "coverage_rate": tr.coverage_rate,
                    "entries": [
                        {
                            "test_case_id": e.test_case_id,
                            "description": e.description,
                            "implemented_by": e.implemented_by,
                            "is_covered": e.is_covered,
                            "notes": e.notes,
                        }
                        for e in tr.entries
                    ],
                }

            traceability_data["segments"].append(segment_trace)

        traceability_path = run_dir / "traceability_report.json"
        with open(traceability_path, "w", encoding="utf-8") as f:
            json.dump(traceability_data, f, indent=2)
        written_files["traceability_report"] = str(traceability_path)
        logger.info(f"Saved traceability report: {traceability_path}")

        # ── 4. Save run summary ────────────────────────────────────────────
        summary_data = {
            "run_id": output.run_id,
            "generated_at": timestamp,
            "segments_processed": output.segments_processed,
            "segments_with_valid_tests": output.segments_with_valid_tests,
            "success_rate": output.success_rate,
            "errors": output.errors,
            "output_files": written_files["test_files"],
            "review_report": written_files["review_report"],
            "traceability_report": written_files["traceability_report"],
        }

        summary_path = run_dir / "run_summary.json"
        with open(summary_path, "w", encoding="utf-8") as f:
            json.dump(summary_data, f, indent=2)
        written_files["summary"] = str(summary_path)
        logger.info(f"Saved run summary: {summary_path}")

        return written_files