# Auto-generated by R26-SE-038 Component 3
# Function : calculate_average
# Source   : sample_project/calculator.py
# Valid    : True
# Repairs  : 0
# Run ID   : demo-run-001

import pytest
from sample_project.calculator import calculate_average

def test_calculate_average_normal_case():
    numbers = [1, 2, 3, 4, 5]
    assert calculate_average(numbers) == 3

def test_calculate_average_empty_list():
    numbers = []
    with pytest.raises(ZeroDivisionError):
        calculate_average(numbers)

def test_calculate_average_single_element():
    numbers = [5]
    assert calculate_average(numbers) == 5

def test_calculate_average_negative_numbers():
    numbers = [-1, -2, -3, -4, -5]
    assert calculate_average(numbers) == -3

def test_calculate_average_mixed_numbers():
    numbers = [-1, 2, -3, 4, -5]
    assert calculate_average(numbers) == -0.6

def test_calculate_average_float_numbers():
    numbers = [1.5, 2.5, 3.5, 4.5, 5.5]
    assert calculate_average(numbers) == 3.5

def test_calculate_average_large_numbers():
    numbers = [1000000, 2000000, 3000000, 4000000, 5000000]
    assert calculate_average(numbers) == 3000000

def test_calculate_average_non_numeric_input():
    numbers = [1, 2, '3', 4, 5]
    with pytest.raises(TypeError):
        calculate_average(numbers)