# Auto-generated by R26-SE-038 Component 3
# Function : calculate_average
# Source   : sample_project/calculator.py
# Valid    : True
# Repairs  : 0
# Run ID   : demo-run-001

import pytest
from sample_project.calculator import calculate_average

def test_calculate_average_normal_case():
    numbers = [1, 2, 3, 4, 5]
    assert calculate_average(numbers) == 3

def test_calculate_average_empty_list():
    numbers = []
    with pytest.raises(ZeroDivisionError):
        calculate_average(numbers)

def test_calculate_average_single_element_list():
    numbers = [5]
    assert calculate_average(numbers) == 5

def test_calculate_average_negative_numbers():
    numbers = [-1, -2, -3, -4, -5]
    assert calculate_average(numbers) == -3

def test_calculate_average_mixed_numbers():
    numbers = [1, -2, 3, -4, 5]
    assert calculate_average(numbers) == 0.6

def test_calculate_average_float_numbers():
    numbers = [1.1, 2.2, 3.3, 4.4, 5.5]
    assert calculate_average(numbers) == 3.3

def test_calculate_average_large_numbers():
    numbers = [1000, 2000, 3000, 4000, 5000]
    assert calculate_average(numbers) == 3000