# TestingContextGenerator converts static analysis results
# into ML-ready features and LLM-ready testing recommendations.
# This is the novelty/intelligence layer of the component.
class TestingContextGenerator:

    def __init__(self, function_complexities, function_dependencies, risk_results):

        # Per-function cyclomatic complexity values
        # Example: {"login": 3, "validate_user": 1}
        self.function_complexities = function_complexities

        # Function dependency mapping
        # Example: {"login": ["validate_user", "connect_db"]}
        self.function_dependencies = function_dependencies

        # Risk result generated by RiskDetector
        # Example: {"login": {"complexity": 3, "dependency_count": 2, "risk_level": "Medium"}}
        self.risk_results = risk_results

    # Main method that creates ML-ready and LLM-ready output
    def generate(self):

        # Stores structured numerical/categorical features for ML use
        ml_ready_features = []

        # Stores testing recommendations for LLM/test generation use
        llm_test_recommendations = []

        # Process each analyzed function
        for function_name, risk_data in self.risk_results.items():

            # Extract risk-related values
            complexity = risk_data["complexity"]
            dependency_count = risk_data["dependency_count"]
            risk_level = risk_data["risk_level"]

            # Get dependency list for the current function
            dependencies = self.function_dependencies.get(function_name, [])

            # Create ML-ready feature object
            ml_ready_features.append({
                "function_name": function_name,
                "cyclomatic_complexity": complexity,
                "dependency_count": dependency_count,
                "risk_level": risk_level
            })

            # Generate suggested testing focus areas
            suggested_focus = self._get_test_focus(
                complexity,
                dependency_count,
                risk_level
            )

            # Create LLM-ready recommendation object
            llm_test_recommendations.append({
                "function": function_name,
                "risk_level": risk_level,
                "reason": self._generate_reason(
                    complexity,
                    dependency_count,
                    risk_level
                ),
                "dependencies": dependencies,
                "suggested_test_focus": suggested_focus
            })

        # Final intelligent testing context output
        return {
            "ml_ready_features": ml_ready_features,
            "llm_test_recommendations": llm_test_recommendations
        }

    # Generates a readable reason explaining why a function has its risk level
    def _generate_reason(self, complexity, dependency_count, risk_level):

        reasons = []

        # Add complexity-based explanation
        if complexity >= 4:
            reasons.append("high cyclomatic complexity")
        elif complexity == 3:
            reasons.append("moderate cyclomatic complexity")

        # Add dependency-based explanation
        if dependency_count >= 3:
            reasons.append("high dependency count")
        elif dependency_count == 2:
            reasons.append("moderate dependency count")

        # If no major issue is detected, mark as low structural complexity
        if not reasons:
            reasons.append("low structural complexity")

        # Return final readable reason
        return f"{risk_level} risk due to " + " and ".join(reasons)

    # Suggests what testing areas should be focused on
    def _get_test_focus(self, complexity, dependency_count, risk_level):

        focus = []

        # Complex functions need branch and edge case testing
        if complexity >= 3:
            focus.extend([
                "branch coverage",
                "edge cases",
                "multiple execution paths"
            ])

        # Functions with many dependencies need dependency/integration tests
        if dependency_count >= 2:
            focus.extend([
                "dependency behavior",
                "mocking external/internal calls",
                "integration-related scenarios"
            ])

        # Low-risk functions only need basic correctness testing
        if risk_level == "Low":
            focus.append("basic functional correctness")

        # Remove duplicates while keeping order
        return list(dict.fromkeys(focus))